# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  rebecca = {
    pname = "rebecca";
    version = "11329a8eb7f3b85ae4585ea3f5e62343f612d5be";
    src = fetchFromGitHub {
      owner = "vic";
      repo = "zellij-rebecca-theme";
      rev = "11329a8eb7f3b85ae4585ea3f5e62343f612d5be";
      fetchSubmodules = false;
      sha256 = "sha256-z5YgUSl/5s8XY1fm1hpnRAG1owrEIMMGBoGN1Mj6ZJg=";
    };
    date = "2024-06-26";
  };
  rose-pine = {
    pname = "rose-pine";
    version = "53835422f965e6c88b9ad59e11d343ca4552bf6d";
    src = fetchFromGitHub {
      owner = "rose-pine";
      repo = "zellij";
      rev = "53835422f965e6c88b9ad59e11d343ca4552bf6d";
      fetchSubmodules = false;
      sha256 = "sha256-VNqd1Qt6LibK7M8KirUhtwpVYAvsgn2e96wAf/YMQzI=";
    };
    date = "2024-01-11";
  };
  sobrio = {
    pname = "sobrio";
    version = "ccf26be71cfe9d20796e8c661234443b2b2e10f1";
    src = fetchFromGitHub {
      owner = "elvessousa";
      repo = "sobrio-zellij";
      rev = "ccf26be71cfe9d20796e8c661234443b2b2e10f1";
      fetchSubmodules = false;
      sha256 = "sha256-YL0xDJUtc66rP/ac8v1n/9xe1NtRVrR8f5JYQmaI//8=";
    };
    date = "2023-06-22";
  };
  zellij = {
    pname = "zellij";
    version = "489c4da5ffaf38526b76bad4ce09da63ae99331e";
    src = fetchFromGitHub {
      owner = "zellij-org";
      repo = "zellij";
      rev = "489c4da5ffaf38526b76bad4ce09da63ae99331e";
      fetchSubmodules = false;
      sha256 = "sha256-uvlUSaQQpc8DIPBFf3h/NtwqJAUp6B4uQ4eWYt25xpM=";
    };
    date = "2024-08-29";
  };
}
