name: Automatically update
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 3 * * *"

jobs:
  nvfetcher:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: Cache nvfetcher
      uses: actions/cache@v4
      with:
        path: ~/.local/share/nvfetcher
        key: ${{ runner.os }}-nvfetcher
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run nvfetcher
      run: nix develop --command nvfetcher

    - name: Run flake check
      run: nix flake check

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ${{ env.COMMIT_MSG }}